#!/bin/bash

mkdir -p /Library/Application\ Support/AirWatch/Data/Munki/Managed\ Installs/Logs/ && touch /Library/Application\ Support/AirWatch/Data/Munki/Managed\ Installs/Logs/ManagedSoftwareUpdate.log

LA="/Library/LaunchAgents/com.vmware.ws1.depnotify.plist"
notifylog="/private/var/tmp/depnotify.log"

echo "Command: Image: /tmp/Workspace ONE/DEPNotify/logo.png" >> $notifylog
echo "Command: MainText: Initializing WS1 Hub and loading custom settings.  This may take 1 to 2 minutes." >> $notifylog
echo "Command: DeterminateOff:" >> $notifylog
echo "Status:  " >> $notifylog

# Get current user uid and start the LaunchAgent as that user.
# This is only needed for Non-DEP scenarios in which the LaunchAgent is
# placed while user session is already active.
# uid=$(/usr/bin/stat -f %u /dev/console)
# This is the Apple recommended way to get the current user
uid=$(python -c 'from SystemConfiguration import SCDynamicStoreCopyConsoleUser; import sys; username = SCDynamicStoreCopyConsoleUser(None, None, None)[1]; sys.stdout.write(str(username) + "\n");')
if [ $uid -gt 500 ];
  then
    /bin/launchctl asuser $uid /bin/launchctl load $LA
fi
