#!/bin/bash
currentUser=`ls -l /dev/console | awk {' print $3 '}`

su $currentUser -c '/usr/bin/defaults -currentHost write com.apple.screensaver moduleDict -dict moduleName "Message" path "/System/Library/Frameworks/ScreenSaver.framework/Resources/Computer Name.saver" type 0'

su $currentUser -c '/usr/bin/defaults -currentHost write com.apple.screensaver.basic MESSAGE "This is my test message."'

su $currentUser -c '/usr/bin/defaults -currentHost write com.apple.screensaver idleTime -int 300'
su $currentUser -c '/usr/bin/defaults -currentHost write com.apple.screensaver showClock 1'

killall cfprefsd

echo "Success"