# Customize Computer Name using Username
<# The computer name is randomly generated by default so that every system coming from the factory is unique. 
To create a naming convention, use the Registered Owner and Registered Organization settings. The computer name 
takes the first 7 characters from Registerd Organization or Registered Owner as the prefix and then randomizes 
the rest of the characters up to the 15 character maximum. #>
# You can leverage First Logon Commands to rename the computer using the serial number. Remember the computer name cannot exceed 15 characters. 

# Below are some samples mixing characters with serial number. In the below example the serial number is 013332272458.
# Ensure your output generates at least 15 characters or modify the command line to only take a smaller number of characters. 

# Base Rename Computer Command
PowerShell Rename-Computer -NewName "New_Computer_Name_Less_Than_15_Characters" -Force

#Example - using username + serial number
PowerShell Rename-Computer -NewName "$env:UserName-$((gwmi Win32_BIOS).SerialNumber)".Substring(0,15)
#Output - jnegron-0133322

#Example - using username + random numbers
PowerShell Rename-Computer -NewName "$env:UserName-$(Get-Random -Minimum 100000000000)".Substring(0,15)
#Output - jnegron-2941613
